### ISSUE TITLE
Implement signature-based authorization for write-operations

### ISSUE THREAD

**Issue by edulix** [sequentech/bulletin-board#8]
```[tasklist]
### Tasks
- [x] Remove sequence id from entries since this limits future potential scalability.
- [x] Implement strand's signatures-based permission system for creating boards at service level and for managing write operations in boards.
- [x] Verify strand signatures in write operations `CreateBoard`, `AddEntries`.
- [x] Make current unit tests work and benches work.
- [x] Make example work and update README accordingly.
- [x] Add unit tests for permission system and signed write operations.
- [x] Fix Github Actions
- [x] Change `ArchiveBoard` action to `ModifyBoard` and use permissions for that too
```

```[tasklist]
# PRs
- https://github.com/sequentech/strand/pull/84
- [ ] https://github.com/sequentech/strand/pull/84
```

Some links:
- https://github.com/hyperium/tonic/blob/master/examples/src/authentication/server.rs
- https://tms-dev-blog.com/jwt-security-for-a-rust-rest-api/
- https://www.ory.sh/docs/oathkeeper/
